version: '2'

services:
  webapiapplication:
    container_name: webapiapplication
    image: webapiapplication
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - webapi-network

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - webapi-network

networks:
  webapi-network:
    driver: bridge